### ISSUE TITLE
Event argument support in xcl_memcpy_to/from_device() API

### ISSUE THREAD

**Issue by heeranand** [Xilinx/SDAccel_Examples#10]
Current implement of xcl_memcpy_to/from_device() does not allow user to supply event as argument.  This could be needed for a design where host and kernels are running together to get better throughput.

**Comment by Spenser309** [comment]
Yes, but why not use clEnqueueRead/Write directly in this case?

**Comment by Spenser309** [comment]
Fixed by using clEnqueueRead/Write in this case
