### ISSUE TITLE
Different values of local and global size support for xcl_run_kernel3d() API

### ISSUE THREAD

**Issue by heeranand** [Xilinx/SDAccel_Examples#11]
Current implementation of xcl_run_kernel3d() takes identical values for local and global size. Ideally user should have option to specify global and local size.

**Comment by Spenser309** [comment]
Yes, but why not use clEnqueueNDRange directly in that case?

**Comment by Spenser309** [comment]
Resolved by using clEnqueueNDRange in this case.
