### ISSUE TITLE
 xbinst support in Makefile

### ISSUE THREAD

**Issue by heeranand** [Xilinx/SDAccel_Examples#12]
Hi,
Can we add xbinst support in Makefile? I guess when user is creating design for hardware, user need runtime drivers to run on board (or nimbix cloud). It is better if we add one make target to run xbinst to generate target DSA package.

**Comment by Spenser309** [comment]
Yes this would be great to add specifically wrt issue #6

**Comment by Spenser309** [comment]
Fixed by modifying Nimbix to not need a local runtime directory.
