### ISSUE TITLE
Cannot upgrade to invalid target ''

### ISSUE THREAD

**Issue by inthesunxkz** [Xilinx/SDAccel_Examples#23]
when I make my rtl logic, I get the error:
ERROR: [XOCC 19-98] Generation of the IP CORE failed.
Cannot upgrade to invalid target ''
How should I to solve it? Thanks.

**Comment by akasat** [comment]
Hi,
Which version of SDAccel are you running the test with. And what is the target platform? Can you share the full makefile command you are using?

Regards,
Amit

**Comment by inthesunxkz** [comment]
@akasat Hi!
The version of SDaccel is 2017.1 and the devices is adm-pcie-7v3.
Thanks

**Comment by heeran-xilinx** [comment]
Hi @inthesunxkz ,
I would suggest if you can send your query to Xilinx SDAccel forum?
https://forums.xilinx.com/t5/SDAccel/bd-p/SDx

There you may get quick support as xilinx Technical support team is actively following the forum queries. 

-Heera
