### ISSUE TITLE
Can I apply it on SDSoc based on ZCU102

### ISSUE THREAD

**Issue by kouyss** [Xilinx/SDAccel_Examples#26]
Hi! I got two problems.

1. Can I apply it on SDSoc based on ZCU102

2.Following the UG1021, I choose zcu102（I don't have a KCU1500 and SDAccel license）, and the software platform are as follows:System configuration:A53 OpenCL Linux;Runtime:OpenCL（make it more similar to the kcu1500）,  and there was a problem in adding SDx Examples, I press the button "Download" for the SDAccel Examples(or the SDSoc Examples), An error windows popped up,“Download Error”:Couldn't download https://github.com/Xilinx/SDAccel_Examples.git.
Do you know the solution?

Regards

**Comment by dutchalthoff** [comment]
@kouyss 
Which version of SDx are you running?

**Comment by heeran-xilinx** [comment]
Hi @kouyss ,

Most of SDAccel examples are not directly compatible to SDSoC platform.  Xilinx is maintaining separate Git repository for SDSoC Specific example, please refer below link:
https://github.com/Xilinx/SDSoC_Examples
Note: OpenCL specific designs are placed under "ocl" folder. These examples are also downloadable from SDx Gui.

As Dutch also requested, what tool version are you using? There were some issues with previous version of tools (2017.1/.2) which are specific to Git Version.  can you try the latest tool 2017.4 sdx?

-Heera

**Comment by kouyss** [comment]
@dutchalthoff @heeran-xilinx
Actually I used the latest tool 2017.4 sdx, and I encountered the same problem when I press "download" button of SDSoc_Examples.
Regards

**Comment by heeran-xilinx** [comment]
Hi @kouyss ,
We tested 2017.4 sdx release and not able to reproduce the issue what you reported. I would suggest if you can post your query to Xilinx SDAccel forum? 
https://forums.xilinx.com/t5/SDAccel/bd-p/SDx

You may get quick support there as lot of support teams are following queries on forum. 

-Heera
