### ISSUE TITLE
a lapse 

### ISSUE THREAD

**Issue by lyons-zhang** [Xilinx/SDAccel_Examples#28]
https://github.com/Xilinx/SDAccel_Examples/wiki/Run-your-first-SDAccel-program-on-AWS-F1
“$ SDACCEL_DIR/tools/create_sdaccel_afi.sh \”  should be 
"$ $SDACCEL_DIR/tools/create_sdaccel_afi.sh \".

**Comment by dutchalthoff** [comment]
Fixed in [0316316](https://github.com/Xilinx/SDAccel_Examples/wiki/Run-your-first-SDAccel-program-on-AWS-F1/0316316ffd059c6d95e1970d672b47a5be1accca)
