### ISSUE TITLE
HLS C-Kernel Support

### ISSUE THREAD

**Issue by heeranand** [Xilinx/SDAccel_Examples#3]
I guess current Makefile flow does not support HLS C-Kernel. Can we enhance Makefile flow to support this?

**Comment by heeranand** [comment]
Makefile Enhancement for HLS C-Kernel should also consider the mixed Kernel Case (one OpenCL Kernel and one HLS C-Based Kernel).

**Comment by Spenser309** [comment]
Can be done in the current infra by setting <kernel>_XFLAGS . To support multiple kernels define two kernels and add them to the XCLBINS variable. See https://github.com/Xilinx/SDAccel_Examples/blob/master/getting_started/vmul_vadd/Makefile for an example.
