### ISSUE TITLE
Runtime include errors

### ISSUE THREAD

**Issue by definelicht** [Xilinx/SDAccel_Examples#38]
This commit seems to have broken all examples: 3b7e906d36d30ebb7b0e24fccdc04427acb87b31

Compiling any example gives the following error because XILINX_XRT is not set (also there is no possible value of XILINX_XRT that is correct, since it seems to assume a different directory structure from what's in SDAccel 2018.2):

```
% XILINX_SDX=/opt/Xilinx/SDx/2018.2 make exe
mkdir -p ./xclbin
/opt/Xilinx/SDx/2018.2/bin/xcpp -I /include/ -I//opt/Xilinx/SDx/2018.2/Vivado_HLS/include/ -O0 -g -Wall -fmessage-length=0 -std=c++14 -I../../..//libs/xcl2 src/host.cpp ../../..//libs/xcl2/xcl2.cpp -o 'vadd' -lOpenCL -lpthread -lrt -lstdc++ -L/lib/ 
In file included from src/host.cpp:29:0:
../../..//libs/xcl2/xcl2.hpp:47:10: fatal error: CL/cl2.hpp: No such file or directory
 #include <CL/cl2.hpp>
          ^~~~~~~~~~~~
compilation terminated.
In file included from ../../..//libs/xcl2/xcl2.cpp:33:0:
../../..//libs/xcl2/xcl2.hpp:47:10: fatal error: CL/cl2.hpp: No such file or directory
 #include <CL/cl2.hpp>
          ^~~~~~~~~~~~
compilation terminated.
```

What happened?

**Comment by aharishkumar** [comment]
Hi @definelicht , please source the following,

source /opt/Xilinx/SDx/<2018.2>/xbb/xrt/packages/<ubuntu/centos>/opt/xilinx/xrt/setup.<sh/csh>

This sets the XILINX_XRT env variable and this issue must not be seen.

Thanks,
 Harish.

**Comment by definelicht** [comment]
Hi @aharishkumar, thanks for the response.
I did not find this information in the README files of the repository or for the example. I would suggest that you update the documentation to make this more clear :-)

**Comment by heeran-xilinx** [comment]
Closing this issue as filer is able to run after proper setup which are needed for 2018.2_xdf release.

**Comment by vird** [comment]
apt install opencl-headers
That helps me
