### ISSUE TITLE
the application hangs on s_axi_control write transaction

### ISSUE THREAD

**Issue by yangensh** [Xilinx/SDAccel_Examples#40]
Hi, 
I was using waveform for Kernel Debugging in Emulation-HW mode, and found the host app continues issuing write transaction to s_axi_control interface until it hits the write address = 0x354. 
(1) The AW valid signal has been pulled high, but wvalid signal remains low. The s_axi_control interface has no action since then, I think the runtime of my my waveform is long enough, ~450us. Owing to it,  the configuration process hangs, and I could not see ap_start pulse. I have no idea why this happens.  
(2) In our kernel.xml, we have defined 136 arguments for our kernel. Some are bonded with s_axi_control port, with address 4bytes aligned, while others are bonded with m00_axi port, with address 8-bytes aligned. 
(3) In our Emulation console, it prints the following information.

```
platform Name: Xilinx
Vendor Name : Xilinx
Found Platform
XCLBIN File Name: v2mc
INFO: Importing ../v2mc.xclbin
Loading: '../v2mc.xclbin'
INFO: [SDx-EM 01] Hardware emulation runs simulation underneath. Using a large data set will result in long simulation times. It is recommended that a small dataset is used for faster execution. This flow does not use cycle accurate models and hence the performance data generated is approximate.
INFO: [SDx-EM 22] [Wall clock time: 00:13, Emulation time: 0.00388295 ms] Data transfer between kernel(s) and global memory(s)
v2mc_1:m00_axi          RD = 0.000 KB               WR = 0.000 KB    

INFO: [SDx-EM 22] [Wall clock time: 00:18, Emulation time: 0.00810919 ms] Data transfer between kernel(s) and global memory(s)
v2mc_1:m00_axi          RD = 0.000 KB               WR = 0.000 KB        

INFO: [SDx-EM 22] [Wall clock time: 00:24, Emulation time: 0.0123588 ms] Data transfer between kernel(s) and global memory(s)
v2mc_1:m00_axi          RD = 0.000 KB               WR = 0.000 KB        

INFO: [SDx-EM 22] [Wall clock time: 00:29, Emulation time: 0.0165217 ms] Data transfer between kernel(s) and global memory(s)
v2mc_1:m00_axi          RD = 0.000 KB               WR = 0.000 KB        

INFO: [SDx-EM 22] [Wall clock time: 00:34, Emulation time: 0.0209012 ms] Data transfer between kernel(s) and global memory(s)
v2mc_1:m00_axi          RD = 0.000 KB               WR = 0.000 KB        

INFO: [SDx-EM 22] [Wall clock time: 00:39, Emulation time: 0.0253441 ms] Data transfer between kernel(s) and global memory(s)
v2mc_1:m00_axi          RD = 0.000 KB               WR = 0.000 KB        

INFO: [SDx-EM 22] [Wall clock time: 00:44, Emulation time: 0.0297537 ms] Data transfer between kernel(s) and global memory(s)
v2mc_1:m00_axi          RD = 0.000 KB               WR = 0.000 KB        

ERROR: buffer (44) is not resident in device (0)
```

(4) In the above design, there are 4 processing units, with 34x4 configuration registers inside kernel.xml and settings for 34x4 kernel arguments in host.cpp. But when I modify kernel.xml and host.cpp just for 1 processing unit, the simulation pass. I thought there might be error in software. But I am not so sure about it.

Could anyone give me some guidance to address the issue ?

**Comment by heeran-xilinx** [comment]
HI @yangensh ,
Please post General query related to SDAccel on Xilinx Forum:
https://forums.xilinx.com/t5/SDAccel/bd-p/SDx

-Heera
