### ISSUE TITLE
Issues with Using printf() to Debug Kernels

### ISSUE THREAD

**Issue by ArmenLevoni** [Xilinx/SDAccel_Examples#41]
Hi,
I am trying using printf() to debug Kernels, according to:
https://china.xilinx.com/support/documentation/sw_manuals/xilinx2018_2/ug1281-sdaccel-debugging-guide.pdf

The kernel code is from helloworld_ocl example:
`#define BUFFER_SIZE 256
kernel __attribute__((reqd_work_group_size(1, 1, 1)))
void vector_add(global int* c,
                global const int* a,
                global const int* b,
                       const int n_elements)
{
    int arrayA[BUFFER_SIZE];
    int arrayB[BUFFER_SIZE];
    printf("BUFFER_SIZE is %d\n", BUFFER_SIZE);
    printf("n_elements is %d\n", n_elements);
    printf("Some number is is %d\n", 55);

    for (int i = 0 ; i < n_elements ; i += BUFFER_SIZE)
    {
        int size = BUFFER_SIZE;
        printf("Current i is %d\n", i);
        if (i + size > n_elements) size = n_elements - i;
        readA: for (int j = 0 ; j < size ; j++) arrayA[j] = a[i+j];
        readB: for (int j = 0 ; j < size ; j++) arrayB[j] = b[i+j];
        vadd_writeC: for (int j = 0 ; j < size ; j++) c[i+j] = arrayA[j] + arrayB[j];
    }
}`

The command I run on AWS F1 instance is:
make check TARGETS=sw_emu DEVICES=$AWS_PLATFORM all

The result is:

> BUFFER_SIZE is 8
> n_elements is 8
> Some number is is 8
> Current i is 8

As you can see all are 8, not sure why.
Can you please help me to figure out how to use printf()?

**Comment by heeran-xilinx** [comment]
Hi @ArmenLevoni ,
for General SDAccel related queries, could you please post your query to Xilinx Forum for quick response:
https://forums.xilinx.com/t5/SDAccel/bd-p/SDx

We have tried the same locally and found it working as below:
Found Platform
Platform Name: Xilinx
Found Device=xilinx_aws-vu9p-f1-04261818_dynamic_5_0
XCLBIN File Name: vector_addition
INFO: Importing xclbin/vector_addition.sw_emu.xilinx_aws-vu9p-f1-04261818_dynamic_5_0.xclbin
Loading: 'xclbin/vector_addition.sw_emu.xilinx_aws-vu9p-f1-04261818_dynamic_5_0.xclbin'
BUFFER_SIZE is 256
n_elements is 256
Some number is is 55
Current i is 0
Result = 
42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 
42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 
42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 
42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 
42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 
42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 
42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 
42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 
42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 
42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 
42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 
42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 
42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 
42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 
42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 
42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 
TEST PASSED

If you still face the same error, I would recommend to post your query to Xilinx forum with test files.

-Heera
