### ISSUE TITLE
possible bug in "Systolic Arrays (CL)" example

### ISSUE THREAD

**Issue by salehjg** [Xilinx/SDAccel_Examples#42]
I was checking out the mentioned example and I noticed this:

https://github.com/Xilinx/SDAccel_Examples/blob/1e273f6ef01073f878a4c2b5ca4d6ad5aec7e616/getting_started/kernel_opt/systolic_array_ocl/src/mmult.cl#L91

Am I missing something? Isn't dimension supposed to be the non zero index of array's dimension(1 to N)? here it's zero which doesn't make sense.  (according to the [SDx Pragma Reference Guide](https://japan.xilinx.com/html_docs/xilinx2017_4/sdaccel_doc/kal1504034361186.html))

There is this comment in the code about local matrix C being partitioned completely(maybe by setting dimension to zero) but nothing on the document explains such capability.

**Comment by heeran-xilinx** [comment]
Hi @salehjg ,
Thanks for reporting this issue. Seems like issue with documentation. Here 0 means all dimension. so array will be partition for all dimension. Following is the vivado_hls.log report:

INFO: [XFORM 203-101] Partitioning array 'localC' (./src/mmult.cl:91) in dimension 1 completely.
INFO: [XFORM 203-101] Partitioning array 'localC' (./src/mmult.cl:91) in dimension 2 completely.
I will report this documentation issue internally.

-Heera
