### ISSUE TITLE
how to generate waveform in example "getting_started/kernel_gmem/burst_rw_c" ?

### ISSUE THREAD

**Issue by xiaoliang201188** [Xilinx/SDAccel_Examples#47]
There was no "*.wdb" file when I used "make all TARGET=hw_emu DEVICE=xilinx_u200_xdma_201820_1" to build .

**Comment by xiaoliang201188** [comment]
![image](https://user-images.githubusercontent.com/44012418/57360526-f463b700-71ac-11e9-8654-5836d22dc7c1.png)

**Comment by kapil2099** [comment]
Hi , sorry for the late reply.

To only save .wdb file 
Please include following in your sdaccel.ini :

[Emulation]
launch_waveform=batch 

To save .wdb as well as view it in GUI
Please include following in your sdaccel.ini :

[Emulation]
launch_waveform=gui

**Comment by heeran-xilinx** [comment]
HI @xiaoliang201188 ,
Please refer this example which dump .wdb file. I has sdaccel.ini containing required information for the same.

-Heera

**Comment by xiaoliang201188** [comment]
Solved , Thank you!
