### ISSUE TITLE
Using 4 ddr banks in rtl kernel in Sdaccel 2019.1 on Alevo U200

### ISSUE THREAD

**Issue by lhh1389** [Xilinx/SDAccel_Examples#51]
Hi 
    I  use 6 MAXI interfaces in the rtl design, I can use 4 ddr banks max on U200, so I reuse the banks. I have 8 buffers to place in the 4 ddr banks. The code is as below. When exectuting to cl:Buffer line, below error is called：

ERROR: bad host_ptr of mem use flags
src/host.cpp:1051 Error calling cl::Buffer buffer_cnn_fmap(context,CL_MEM_USE_HOST_PTR | CL_MEM_READ_ONLY | CL_MEM_EXT_PTR_XILINX, cnn_fmap_len, &GlobMem_BUF_output_Ext, &err), error code is: -37
what is the problem? what should I do to reuse the ddr banks correctly? Thanks!
The platform is xilinx_u200_xdma_201830_1\/xilinx_u200_xdma_201830_1.xpfm and SDx version is 2019.1. 
host.cpp code:

cl_mem_ext_ptr_t ddr0;
ddr0.param = krnl_deepspeech2.get();
ddr0.flags = 0;
ddr0.obj = 0;

cl_mem_ext_ptr_t ddr1;
ddr1.param = krnl_deepspeech2.get();
ddr1.flags = 1;
ddr1.obj = 0;

cl_mem_ext_ptr_t ddr2;
ddr2.param = krnl_deepspeech2.get();
ddr2.flags = 2;
ddr2.obj = 0;

cl_mem_ext_ptr_t ddr3;
ddr3.param = krnl_deepspeech2.get();
ddr3.flags = 3;
ddr3.obj = 0;

OCL_CHECK(err, cl::Buffer buffer_cnn_krnl(context,CL_MEM_USE_HOST_PTR | CL_MEM_READ_ONLY | CL_MEM_EXT_PTR_XILINX, cnn_krnl_len, &ddr1, &err));
OCL_CHECK(err, cl::Buffer buffer_cnn_fmap(context,CL_MEM_USE_HOST_PTR | CL_MEM_READ_ONLY | CL_MEM_EXT_PTR_XILINX, cnn_fmap_len, &ddr2, &err));
OCL_CHECK(err, cl::Buffer buffer_cnn_yout (context,CL_MEM_USE_HOST_PTR | CL_MEM_WRITE_ONLY | CL_MEM_EXT_PTR_XILINX, cnn_output_len, &ddr2, &err));
OCL_CHECK(err, cl::Buffer buffer_blstm_ddr0(context, CL_MEM_USE_HOST_PTR | CL_MEM_READ_ONLY | CL_MEM_EXT_PTR_XILINX, blstm_ddr0_len, &ddr0, &err));
OCL_CHECK(err, cl::Buffer buffer_blstm_ddr1(context, CL_MEM_USE_HOST_PTR | CL_MEM_READ_ONLY | CL_MEM_EXT_PTR_XILINX, blstm_ddr1_len, &ddr1, &err));
OCL_CHECK(err, cl::Buffer buffer_blstm_ddr2(context, CL_MEM_USE_HOST_PTR | CL_MEM_READ_ONLY | CL_MEM_EXT_PTR_XILINX, blstm_ddr2_len, &ddr2, &err));
OCL_CHECK(err, cl::Buffer buffer_blstm_ddr3(context, CL_MEM_USE_HOST_PTR |CL_MEM_READ_ONLY | CL_MEM_EXT_PTR_XILINX, blstm_ddr3_len, &ddr3, &err));
OCL_CHECK(err, cl::Buffer buffer_blstm_yout(context, CL_MEM_USE_HOST_PTR | CL_MEM_WRITE_ONLY | CL_MEM_EXT_PTR_XILINX, blstm_output_len, &ddr1, &err));

q.enqueueWriteBuffer(buffer_cnn_krnl,CL_TRUE,0,cnn_krnl_len,cnn_krnl_buff);
q.enqueueWriteBuffer(buffer_cnn_fmap,CL_TRUE,0,cnn_fmap_len,cnn_fmap_buff);
q.enqueueWriteBuffer(buffer_blstm_ddr0,CL_TRUE,0,blstm_ddr0_len,blstm_ddr0_buff);
q.enqueueWriteBuffer(buffer_blstm_ddr1,CL_TRUE,0,blstm_ddr1_len,blstm_ddr1_buff);
q.enqueueWriteBuffer(buffer_blstm_ddr2,CL_TRUE,0,blstm_ddr2_len,blstm_ddr2_buff);
q.enqueueWriteBuffer(buffer_blstm_ddr3,CL_TRUE,0,blstm_ddr3_len,blstm_ddr3_buff);
 Make file code:

(XCLBIN)/deepspeech2.$(TARGET).$(DSA).xclbin: $(BINARY_CONTAINER_deepspeech2_OBJS)
mkdir -p $(XCLBIN)
$(XOCC) $(CLFLAGS) $(LDCLFLAGS) -lo $(XCLBIN)/deepspeech2.$(TARGET).$(DSA).xclbin $(XCLBIN)/deepspeech2.$(TARGET).$(DSA).xo --sp DeepSpeech2_TOP_1.M00_AXI:DDR[0] --sp DeepSpeech2_TOP_1.M01_AXI:DDR[1] --sp DeepSpeech2_TOP_1.M02_AXI:DDR[2] --sp DeepSpeech2_TOP_1.M03_AXI:DDR[3] --sp DeepSpeech2_TOP_1.M04_AXI:DDR[1] --sp DeepSpeech2_TOP_1.M05_AXI:DDR[2]

**Comment by heeran-xilinx** [comment]
Hi @lhh1389 ,
For any general query related to SDAccel, please post into Xilinx Forum on below:
https://forums.xilinx.com/t5/SDAccel/bd-p/SDx

You will give quick response there as many SDAccel experts and Support teams are following the forum queries.

-Heera
