### ISSUE TITLE
how to generate waveform in example SDAccel_Examples/getting_started/rtl_kernel/rtl_vadd

### ISSUE THREAD

**Issue by saitej25** [Xilinx/SDAccel_Examples#52]
I've added
"[Emulation]
launch_waveform=gui" in the xrt.ini and build the design. I don't see a GUI coming up when I run the test. 
PS: Command used make DEVICE=xilinx_u200_qdma_201910_1 TARGET=hw_emu check

**Comment by heeran-xilinx** [comment]
Hi @saitej25 ,
Please post such queries to SDx Forum: https://forums.xilinx.com/t5/SDAccel/bd-p/SDx

-Heera
