### ISSUE TITLE
How to connect DDR4 to RTL Kernel

### ISSUE THREAD

**Issue by saitej25** [Xilinx/SDAccel_Examples#53]
I believe the DDR4 memory is used for communication with OpenCL kernel. How can I get a AXI-Master MM to connect to RTL Kernel without disturbing OpenCL space

**Comment by heeran-xilinx** [comment]
hi @saitej25 ,
Please post such queries to SDx Forum for quick response from Xilinx Expert:
https://forums.xilinx.com/t5/SDAccel/bd-p/SDx

-Heera
