### ISSUE TITLE
Not able to build rtl examples 

### ISSUE THREAD

**Issue by saitej25** [Xilinx/SDAccel_Examples#54]
SDAccel_Examples/getting_started/rtl_kernel/rtl_streaming_free_running
Example Design giving errors when I tried to build
make all TARGET=hw_emu DEVICE=xilinx_u200_qdma_201910_1 check

logs:
****** Vivado v2019.1 (64-bit)
  **** SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
  **** IP Build 2548770 on Fri May 24 18:01:18 MDT 2019
    ** Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.

ERROR: /home/stbodank/megh/dcp/workspace/xilinx_shell/SDAccel_Examples/getting_started/rtl_kernel/rtl_streaming_free_running/pinfo.json does not exist!
couldn't open "/home/stbodank/megh/dcp/workspace/xilinx_shell/SDAccel_Examples/getting_started/rtl_kernel/rtl_streaming_free_running/pinfo.json": no such file or directory
    while executing
"open $pinfo r"
    invoked from within
"set fid [open $pinfo r]"
    (file "./src/gen_xo.tcl" line 59)
INFO: [Common 17-206] Exiting Vivado at Mon Aug  5 11:13:43 2019...
config.mk:3: recipe for target 'xclbin/myadder1.hw_emu.xilinx_u200_qdma_201910_1.xo' failed
make: *** [xclbin/myadder1.hw_emu.xilinx_u200_qdma_201910_1.xo] Error 1

**Comment by rajatsarkari** [comment]
Hi @saitej25 ,
Could you please give the complete path to the .xpfm file in the DEVICE section?
For example: make all TARGET=hw_emu DEVICE=<PATH_TO_DEVICE>/xilinx_u200_qdma_201910_1/xilinx_u200_qdma_201910_1.xpfm check
Regards,
Rajat Sarkari

**Comment by jstonge640** [comment]
I am having the same problem when trying to compile `rtl_streaming_free_running` on the nimbix cloud.  I tried using the absolute path as suggested and I ran into another error (see snippet below).  Please see [vivado.log](https://github.com/Xilinx/SDAccel_Examples/files/3642115/vivado.log) for the complete log file.

`Creating apsys_0.xml
ERROR: [CFGEN 83-2284] No stream resources found that can accomodate compute unit "myadder1_1"
Error generating design file for apsys_0.xml
command: /opt/xilinx/SDx/2019.1/bin/cfgen    -r /data/SDAccel_Examples/getting_started/rtl_kernel/rtl_streaming_free_running/_x/link/sys_link/_sds/.cdb/xd_ip_db.xml -o apsys_0.xml
Error creating intermediate design file, exiting
INFO: [XOCC 60-1442] [12:29:57] Run xocc_link: Step sdx_link: Failed
Time (s): cpu = 00:00:07 ; elapsed = 00:00:09 . Memory (MB): peak = 563.199 ; gain = 0.000 ; free physical = 63548 ; free virtual = 196247
ERROR: [XOCC 60-661] xocc link run 'xocc_link' failed
ERROR: [XOCC 60-626] Kernel link failed to complete
ERROR: [XOCC 60-703] Failed to finish linking
Makefile:90: recipe for target 'xclbin/myadder1.hw_emu.xilinx_u200_xdma_201830_2.xclbin' failed
make: *** [xclbin/myadder1.hw_emu.xilinx_u200_xdma_201830_2.xclbin] Error 1`

**Comment by heeran-xilinx** [comment]
rtl_streaming_free_running example is supported only by QDMA platform. 
But as per log it looks like XDMA platform is used:
Please see the supported platform list in readme:
https://github.com/Xilinx/SDAccel_Examples/blob/master/getting_started/rtl_kernel/rtl_streaming_free_running/README.md

**Comment by jstonge640** [comment]
> rtl_streaming_free_running example is supported only by QDMA platform.
> But as per log it looks like XDMA platform is used:
> Please see the supported platform list in readme:
> https://github.com/Xilinx/SDAccel_Examples/blob/master/getting_started/rtl_kernel/rtl_streaming_free_running/README.md

My mistake.  Thanks!  It appears Nimbix doesn't have any QDMA .xpfm platforms installed so I will reach out to them, unless there's another location for that file?

**Comment by jstonge640** [comment]
I believe that the absolute path is still required, so shouldn't this issue remain open?  The `pinfo.json does not exist!` error still persists when trying to use only the device name.

**Comment by saitej25** [comment]
> I believe that the absolute path is still required, so shouldn't this issue remain open? The `pinfo.json does not exist!` error still persists when trying to use only the device name.

git issues in this repo are a joke anyway.

**Comment by heeran-xilinx** [comment]
Re-opening this issue to remove the restriction of absolute path. Which will be addressed in next release. For now, please use absolute path as work-around.

**Comment by shivrajatrialogic** [comment]
I am also facing this issue.
Also the Host.cpp source code doesnt compile.
Throws multiple error:
1. error: static assertion failed: Wrong number of arguments for pointer-to-member
2. functional:1395:9: error: no type named \u2018type\u2019 in \u2018class std::result_of<int (*(_cl_stream*, int*, unsigned int, stream_xfer_req*, int*))(_cl_device_id*, _cl_stream*, const void*, long unsigned int, long unsigned int, stream_xfer_req*, int*)>\u2019 _M_invoke(_Index_tuple<_Indices...>)

I get these errors when  i make :Follows
make check TARGETS=hw_emu DEVICES=Board_name

**Comment by heeran-xilinx** [comment]
This issue has been addressed in new Git repository:
https://github.com/Xilinx/Vitis_Accel_Examples

This repo support Xilinx new Tool Vitis 2019.2
