### ISSUE TITLE
It's err'unable to issue xclExecBuf' when I test the example "hbm_bandwidth" on card u50

### ISSUE THREAD

**Issue by xiaoliang201188** [Xilinx/SDAccel_Examples#55]
I load xclbin by host , but there is no response until 'Creating a kernel ......for CU[8]', 
![image](https://user-images.githubusercontent.com/44012418/65683601-3758f500-e090-11e9-973a-b7423620c2c2.png), 
and  "ctrl+c" to exit the host,  then './host xclbin/*xclbin' again, it's err 
![image](https://user-images.githubusercontent.com/44012418/65683763-b2baa680-e090-11e9-889d-13edc165d353.png).
Howerver, The sw_emu flow worked ok.
![image](https://user-images.githubusercontent.com/44012418/65684147-763b7a80-e091-11e9-88e8-38ed6c047bd7.png)

**Comment by heeran-xilinx** [comment]
Hi @xiaoliang201188 ,
U50 does not support this HBM Bandwidth example as this example power requirement is higher than U50 power limit. Please try this design with lesser number of compute units to fit U50 power limit.
