### ISSUE TITLE
Host streaming example for OpenCL

### ISSUE THREAD

**Issue by scarlehoff** [Xilinx/SDAccel_Examples#56]
I can't help but noticing that all examples for host streaming are for Cpp kernels. Is it not possible to achieve the same functionality with OpenCL kernels?

I'm thinking for instance of `host/streaming_host_bandwidth` or even `host/streaming_simple`.

**Comment by heeran-xilinx** [comment]
Hi @scarlehoff , 
Streaming kernel support is  provided for HLS & RTL kernel only. Please post your query to SDAccel forum to check if OpenCL kernels are planned to support in future or not.

**Comment by heeran-xilinx** [comment]
Closing this as this repository is only for older released version of tool and no more support is available.
Please use latest Repository: https://github.com/Xilinx/Vitis_Accel_Examples for Xilinx latest Tool chain.
