### ISSUE TITLE
Unable to run VADD RTL kernel Example

### ISSUE THREAD

**Issue by ramshankar1990** [Xilinx/SDAccel_Examples#57]
I am trying to run the basic RTL vadd example(https://github.com/Xilinx/SDAccel_Examples/tree/master/getting_started/rtl_kernel/rtl_vadd) using the SDx 2019. I created a kernel using the RTL kernel Wizard exactly as shown in the example and used to host code provided, but I am unable to see the results for both hw_emu and system. The only thing that I am missing is the top level RTL wrapper since I created the kernel using the SDx RTL Kernel Wizard. 

In hw_emu,  get the following error:-
Found Platform
Platform Name: Xilinx
INFO: Reading binary_container_1.xclbin
Loading: 'binary_container_1.xclbin'
FATAL ERROR : Simulation process did not launch
*** Error in `./test_rtl_kernl.exe': double free or corruption (fasttop): 0x00000000012e0810 ***
Segmentation fault

In System, I get the following error:-
Found Platform
Platform Name: Xilinx
INFO: Reading binary_container_1.xclbin
Loading: 'binary_container_1.xclbin'
XRT build version: 2.2.2250
Build hash: dd210161e204e882027d22132725d8ffdf285149
Build date: 2019-09-04 23:27:48
Git branch: 2019.1
PID: 8681
UID: 55026
[XRT] ERROR: Invalid scalar argument size, expected 4 got 8
ERROR: clSetKernelArg() for kernel "krnl_vadd_rtl_int", argument index 0.
../src/host.cpp:97 Error calling err = krnl_vadd.setArg(0, buffer_r1), error code is: -51

I did not clone the repo the run the examples. I copy pasted the code directly from the repo.

Thank you in advance for your help.

**Comment by heeran-xilinx** [comment]
Hi @ramshankar1990 ,

Please post your Query to Xilinx Forum discussion:
https://forums.xilinx.com/t5/Vitis-SDAccel-and-SDSoC/bd-p/tools_v

-Heera
