### ISSUE TITLE
xcl_import_binary() API is not useful incase of multiple different kernels

### ISSUE THREAD

**Issue by heeranand** [Xilinx/SDAccel_Examples#9]
xcl_import_binary() API creates program and one kernel. Incase of multiple different kernels, this API cannot be used multiple times as it will create multiple programs along with multiple kernels. 
So I would suggest to have a separate APIs like xcl_create_program() and xcl_create_kernel(). xcl_create_program() will be used once and xcl_create_kernel() API will be called for each kernel.

**Comment by Spenser309** [comment]
Very true.  Have a patch in my local sandbox for this.

**Comment by Spenser309** [comment]
Fixed.  Now xcl_import_binary returns a cl_program and you can use xcl_get_kernel to pull kernels out of the program.
